#!/usr/bin/env node
const program = require('commander')

program
  .version('0.0.0', '--version')
  .description("CLI to manage my portfolio's database file")
  .command('compile [file] [directory]', 'Compiles a database file')
  .alias('c')
  .command('upload [file] [user]@[host]', 'Uploads the database file via scp')
  .alias('u')
  .parse(process.argv)
